version: "3.8"

name: propercompleteguideproject
services:
  api:
    container_name: api
    build: .
    restart: always
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
  database:
    image: postgres:16.2
    restart: always
    container_name: database
    env_file: ".env"
    user: root
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    ports:
      - 5454:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  pgdata: